#!/usr/bin/env bash
# Installs and configures nginx to listen on port 80 and return a page with "Holberton School"
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
