#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me to another page with 301
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart
